app/base/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (CustomLoginView, DeleteView, LogCreate, LogList, LogUpdate,
                    logplot)

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="login"), name="logout"),
    path("", LogList.as_view(), name="logs"),
    path("log-create/", LogCreate.as_view(), name="log-create"),
    path("log-update/<int:pk>/", LogUpdate.as_view(), name="log-update"),
    path("log-delete/<int:pk>/", DeleteView.as_view(), name="log-delete"),
    path("log-plot/", logplot, name="log-plot"),
]

app/drinklog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
]

app/example/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

app/base/models.py
import os

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Log(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=os.environ.get("ALLOW_NULL_USERS"),
        blank=os.environ.get("ALLOW_BLANK_USERS"),
    )
    date = models.DateField()
    intensity = models.IntegerField(
        default=0, validators=[MaxValueValidator(100), MinValueValidator(0)]
    )
    overdrive = models.BooleanField(default=False)

    def __str__(self):
        return (
            str(self.date) + " | " + str(self.intensity) + " | " + str(self.overdrive)
        )

    class Meta:
        order_with_respect_to = "user"

app/base/forms.py
from django import forms

app/base/views.py
import calendar
import json
import random
from datetime import date, datetime, timedelta

import numpy as np
import pandas as pd
import plotly
import plotly.express as px
from django import forms
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Sum
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import (CreateView, DeleteView, FormView,
                                       UpdateView)
from django.views.generic.list import ListView

from .models import Log


class CustomLoginView(LoginView):
    template_name = "base/login.html"
    fields = "__all__"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("logs")


class LogList(LoginRequiredMixin, ListView):
    model = Log
    context_object_name = "logs"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)

        search_input = self.request.GET.get("search-area") or ""
        if search_input:
            queryset = queryset.filter(date__contains=search_input)

        return queryset.order_by("-date")  # Sort descending by date

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_query"] = self.request.GET.get("search-area", "")
        context["username"] = self.request.user.username
        context["show_pill_links"] = True

        # Choose a random icon for the overdrive col
        icons = [
            "fa-person-falling-burst",
            "fa-skull",
            "fa-skull-crossbones",
            "fa-bolt",
        ]

        context["random_icon"] = random.choice(icons)

        # Calculate #days since last log
        latest_log = self.get_queryset().first()
        if latest_log and latest_log.intensity > 0:
            days_since_last_log = (timezone.now().date() - latest_log.date).days
            context["days_since_last_log"] = days_since_last_log
        else:
            context["days_since_last_log"] = None

        # Sum all intensities of last week/month
        today = timezone.now().date()
        week_ago = today - timedelta(days=7)
        month_ago = today - timedelta(days=30)

        week_intensity_sum = (
            self.get_queryset()
            .filter(date__gte=week_ago)
            .aggregate(Sum("intensity"))["intensity__sum"]
            or 0
        )
        month_intensity_sum = (
            self.get_queryset()
            .filter(date__gte=month_ago)
            .aggregate(Sum("intensity"))["intensity__sum"]
            or 0
        )

        context["week_intensity_sum"] = week_intensity_sum
        context["month_intensity_sum"] = month_intensity_sum

        return context


class LogCreate(LoginRequiredMixin, CreateView):
    model = Log
    fields = ["date", "intensity", "overdrive"]
    success_url = reverse_lazy("logs")

    def form_valid(self, form):
        date = form.cleaned_data["date"]

        # Check if a log with this date exists
        existing_log = Log.objects.filter(date=date, user=self.request.user).first()

        if existing_log:  # Combine them
            existing_log.intensity = min(
                existing_log.intensity + form.cleaned_data["intensity"], 25
            )
            existing_log.overdrive = (
                existing_log.overdrive or form.cleaned_data["overdrive"]
            )
            existing_log.save()
            return redirect(self.success_url)
        else:  # Create a new one
            form.instance.user = self.request.user
            return super(LogCreate, self).form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial["date"] = datetime.now() - timedelta(days=1)
        return initial

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["date"].widget = forms.DateInput(attrs={"type": "date"})
        form.fields["intensity"].widget = forms.TextInput(
            attrs={"type": "range", "min": "0", "max": "25", "value": "0"}
        )
        return form


class LogUpdate(LoginRequiredMixin, UpdateView):
    model = Log
    fields = ["date", "intensity", "overdrive"]
    success_url = reverse_lazy("logs")

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields["date"].disabled = False
        form.fields["date"].widget.attrs["readonly"] = False
        form.fields["date"].widget = forms.DateInput(
            attrs={"type": "date", "readonly": "readonly"}
        )
        form.fields["intensity"].widget = forms.TextInput(
            attrs={"type": "range", "min": "0", "max": "25", "value": "0"}
        )
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["editing"] = True

        return context


class DeleteView(LoginRequiredMixin, DeleteView):
    model = Log
    context_object_name = "log"
    success_url = reverse_lazy("logs")

    def get_queryset(self):
        owner = self.request.user
        return self.model.objects.filter(user=owner)


from datetime import datetime, timedelta


def logplot(request):
    current_user = request.user

    all_logs = Log.objects.all()
    users = [log.user for log in all_logs]
    dates = [log.date for log in all_logs]
    intensities = [log.intensity for log in all_logs]
    overdrives = [log.overdrive for log in all_logs]

    # Create df
    df = pd.DataFrame(
        {
            "user": users,
            "date": dates,
            "intensity": intensities,
            "overdrive": overdrives,
        }
    )

    # Filter for current user
    df = df[df["user"] == current_user]

    # Add color column with black color when overdrive==True
    df["color"] = df["overdrive"].apply(lambda x: "black" if x else "yellow")

    # Normal plot
    fig = px.bar(
        df,
        x="date",
        y="intensity",
        title="",
        labels={"intensity": "Intensity", "date": "Date"},
        color="color",
        color_discrete_map={"black": "#181819", "yellow": "#f2a61e"},
    )
    pre_format_fig(fig)
    fig.update_traces(hovertemplate="<b>Intensity: %{y}</b><br>%{x}<extra></extra>")

    fig.update_xaxes(
        tickformat="%b %d",  # '%b' for short month names
    )

    # Year-section plot
    df["date"] = pd.to_datetime(df["date"])

    min_date = df["date"].min()
    max_date = df["date"].max()

    # Create a df with all dates in the years touched by the df
    date_range = pd.date_range(
        start=min_date.replace(month=1, day=1),
        end=max_date.replace(month=12, day=31),
        freq="D",
    )
    full_df = pd.DataFrame(date_range, columns=["date"])

    # Merge dates
    full_df = pd.merge(full_df, df, on="date", how="left")

    # Fill 'intensity' with 0
    full_df.fillna({"intensity": 0}, inplace=True)

    # Create plot
    fig2 = px.histogram(
        full_df,
        x="date",
        y="intensity",
        histfunc="avg",
        title="",
        nbins=12,
    )
    pre_format_fig(fig2)
    fig2.update_layout(bargap=0.1)

    fig2.update_traces(
        xbins_size="M1",
        marker_color="#f2a61e",
        hovertemplate="<b>Avg Intensity: %{y}</b><extra></extra>",
    )

    fig2.update_xaxes(
        tickformat="%b",  # '%b' for short month names
        dtick="M1",  # show a tick for every month
        tick0="2000-01-15",  # places the ticklabels in the middle of the month
    )

    # Serialize plots
    plot = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    plot_year = json.dumps(fig2, cls=plotly.utils.PlotlyJSONEncoder)

    context = {
        "plot": plot,
        "plot_year": plot_year,
    }

    return render(request, "base/log_plot.html", context)


def pre_format_fig(fig):
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#181819",
        title_font_family="Montserrat",
        coloraxis_showscale=False,
        xaxis_title=None,
        yaxis_title=None,
        showlegend=False,
        margin=dict(l=0, r=30, t=20, b=30),
    )

    fig.update_yaxes(
        showgrid=True,
        gridwidth=1,
        gridcolor="#a6a6ae",
        zeroline=True,
        zerolinecolor="#6f6f75",
    )

    fig.update_traces(
        hoverlabel=dict(
            font_size=16,
            font_family="Montserrat, Jost, sans-serif",
        )
    )

app/base/templates/base/log.html
<h1>Log: {{log}}</h1>

app/base/templates/base/log_confirm_delete.html
{% extends 'base/main.html' %} {% block content %}

<header>
    <a class="h1" href="{% url 'logs' %}">
        <i class="fa-solid fa-arrow-left"></i>
        Delete Log
    </a>
</header>



<div class="content-wrapper">
    <p>Are your sure you want to delete this log?</p>
    <table id="loglist" class="log-list">
        <thead>
            <th>Date</th>
            <th>Intensity</th>
            <th>Overdrive</th>
        </thead>
        <tr>
            <td>{{log.date|date:"d.m.Y"}}</td>
            <td><span style="display: inline-block; width: 1.5em; text-align: right;">{{log.intensity}}</span> <i class="fa-solid fa-xs fa-martini-glass"></i></td>
            <td>
                {% if log.overdrive %}
                    <i id="log-overdrive-icon" class="fa-solid {{ random_icon }} fa-lg"></i>
                {% else %}
                    <i id="log-nooverdrive-icon" class="fa-solid fa-circle" style="font-size: .5em; margin-bottom: 2px;"></i>
                {% endif %}
            </td>
        </tr>
    </table>

    <form method="POST">
        {% csrf_token %}
        <button class="button-danger button-lg" type="submit">
            <i class="fa-regular fa-trash-can"></i>Delete
        </button>
    </form>
</div>

{% endblock content %}

app/base/templates/base/log_form.html
{% extends 'base/main.html' %} {% block content %}


<header>
    <a class="h1" href="{% url 'logs' %}">
        <i class="fa-solid fa-arrow-left"></i>
        {% if editing %}
        Update Log
        {% else %}
        Create Log
        {% endif %}
    </a>
</header>



<div class="content-wrapper">
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group">
            <label class="h5 d-block pt-0" for="id_date">Date:</label>
            {{ form.date }}
        </div>
        <div class="form-group mt-2">
            <label class="h5" for="id_intensity">Intensity: <span class="p" id="intensity-value">0</span></label>
            {{ form.intensity }}
        </div>
        <div class="form-group d-flex align-items-center mt-2">
            <label class="h5 m-0" for="id_overdrive">Overdrive:</label>
            <!-- Pretty checkbox classes hide the actual checkbox generated by django -->
            <div class="pretty p-default p-round ms-1">
                {{ form.overdrive }}
                <!-- This part actually renders the pretty checkbox -->
                <div class="state">
                    <label></label>
                </div>
            </div>
        </div>

        {% if editing %}
        <button class="button-primary button-lg" type="submit"><i class="fa-regular fa-paper-plane"></i>Update</button>
        <a
            class="button button-lg d-block"
            href="{% url 'log-delete' log.id %}"
            ><i class="fa-regular fa-trash-can"></i
        >Delete</a>
        {% else %}
        <button class="button-primary button-lg" type="submit"><i class="fa-regular fa-paper-plane"></i>Submit</button>
        {% endif %}
    </form>

</div>



<script>
    document.addEventListener('DOMContentLoaded', function() {
        var slider = document.getElementById('id_intensity');
        var output = document.getElementById('intensity-value');
        output.innerHTML = slider.value; // Initialwert setzen
    
        slider.oninput = function() {
            output.innerHTML = this.value; // Aktuellen Wert anzeigen
        };
    });
</script>

{% endblock content %}

app/base/templates/base/log_list.html
{% extends 'base/main.html' %} {% block content %}

<div class="dashboard-wrapper">

    <div class="greeting">
        <a href="{% url 'logout' %}">
            Welcome, <strong>{{ username }}</strong>👋🏻
        </a>
    </div>

    <div class="insight-wrapper">
        <h1>Insights</h1>
        <div class="insight-card">
            <p class="fw-semibold"><i class="fa-solid fa-gauge-simple-high"></i> Average</p>
            <h3><strong>{{ week_intensity_sum }}</strong> weekly drinks <span class="text-muted fw-normal" style="font-size: .75rem;">(last 7 days)</span></h3>
            {% if week_intensity_sum != month_intensity_sum %}
            <h3><strong>{{ month_intensity_sum }}</strong> monthly drinks <span class="text-muted fw-normal" style="font-size: .75rem;">(last 31 days)</span></h3>
            {% endif %}
        </div>

        {% if days_since_last_log > 3 %}
        <div class="insight-card">
            <p class="fw-semibold"><i class="fa-solid fa-person-running"></i> Streak</p>
            <h3><strong>{{ days_since_last_log }}</strong>🔥 days since your last entry</h3>
        </div>
        {% endif %}
    </div>
</div>



<div class="log-wrapper">
    <div class="d-flex">
        <h1 class="mt-auto">Your logs</h1>
        <h1 class="d-none logo ms-auto mb-1 me-2">
            <i class="fa-solid fa-sm fa-beer-mug-empty"></i>Drinklog 
        </h1>
        <a class="button-secondary button-outline ms-auto me-2" href="{% url 'log-plot' %}"><i class="fa-solid fa-compass-drafting fa-lg m-auto"></i>Show Plot
        </a>
    </div>

    {% if logs|length > 0 %}
    <table id="loglist" class="log-list">
    {% endif %} {% for log in logs %}
        <tr onclick="window.location='{% url 'log-update' log.id %}';" style="cursor: pointer">

            <td>{{log.date|date:"d/m/Y"}}</td>
            <td><span style="display: inline-block; width: 1.5em; text-align: right;">{{log.intensity}}</span> <i class="fa-solid fa-xs fa-martini-glass"></i></td>
            <td class="text-center text-sm-start" style="margin-right: 1.5rem;">
                {% if log.overdrive %}
                    <i id="log-overdrive-icon" class="fa-solid {{ random_icon }} fa-lg"></i>
                {% else %}
                    <i id="log-nooverdrive-icon" class="fa-solid fa-circle" style="font-size: .5em; margin-bottom: 2px;"></i>
                {% endif %}
            </td>
        </tr>

        {% empty %}
        <div class="mt-2 pb-3 text-center">
            <p class="h4">No logs are created or were matching your query.</p>
            <p class="h4">
                Create a
                <a class="text-primary-light text-decoration-none"
                    href="{% url 'log-create' %}"
                    >new log</a
                >!
            </p>
        </div>
        {% endfor %}
    {% if logs|length > 0 %}
    </table>
    {% endif %}
</div>



<div id="search-overlay" class="search-overlay">
    <div class="search-wrapper">
        <form method="GET" class="d-flex">
        <input
            type="text"
            name="search-area"
            id="search-input"
            class="form-control"
            placeholder="Search your log dates"
            value="{{ search_query }}"
        />

        <button class="btn search-submit" type="submit">
            <i class="fa fa-search"></i>
        </button>
        </form>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const showSearchBtn = document.getElementById('show-search-btn');
    const searchOverlay = document.getElementById('search-overlay');
    const searchContainer = document.querySelector('.search-wrapper');
    const searchInput = document.getElementById('search-input');
    const searchActiveBanner = document.getElementById('search-active-banner');
    const searchTermSpan = document.getElementById('search-term');
    const clearSearchBtn = document.getElementById('clear-search-btn');
    const searchForm = document.querySelector('form');

    showSearchBtn.addEventListener('click', function(e) {
        e.preventDefault();
        searchOverlay.classList.add('active');
        searchInput.focus();
    });

    searchOverlay.addEventListener('click', function(e) {
        if (!searchContainer.contains(e.target)) {
            searchOverlay.classList.remove('active');
        }
    });

    // Prevent that clicking on the search form closes the overlay
    searchContainer.addEventListener('click', function(e) {
        e.stopPropagation();
    });

    function showSearchBanner(searchTerm) {
        searchTermSpan.textContent = searchTerm;
        searchActiveBanner.style.display = 'block';
        setTimeout(() => {
        searchActiveBanner.classList.add('show');
        }, 10);
    }

    function hideSearchBanner() {
        searchActiveBanner.classList.remove('show');
        setTimeout(() => {
        searchActiveBanner.style.display = 'none';
        }, 300);
    }

    // Check if search is active on site loading
    const urlParams = new URLSearchParams(window.location.search);
    const activeSearch = urlParams.get('search-area');
    if (activeSearch) {
        showSearchBanner(activeSearch);
    }

    // event listener for submitting the search form
    searchForm.addEventListener('submit', function(e) {
        const searchTerm = searchInput.value.trim();
        if (searchTerm) {
        showSearchBanner(searchTerm);
        }
    });

    // event listener for clear button in banner
    clearSearchBtn.addEventListener('click', function() {
        hideSearchBanner();
        searchInput.value = '';
        // Optional: Formular absenden, um die Suche zurückzusetzen
        searchForm.submit();
    });
});
</script>



{% include "components/quick_menu.html"%}
{% endblock content %}

app/base/templates/base/login.html
{% extends 'base/main.html' %} {% block content %}

<style>body {background-color: black!important;}</style>
<div class="video-bg" data-vbg="https://www.youtube.com/watch?v=eNQRmNe7Tg4"></div>

<div class="login-wrapper">
    <div class="banner">
        <h1><i class="fa-solid fa-beer-mug-empty fa-xl fa-flip-horizontal"></i></h1>
        <h1 class="fw-bold" style="margin-left: -15px;">Drinklog</h1>
    </div>

    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Login error!</strong><br/>
        Please provide valid credentials.
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label class="h5 pt-0" for="id_username">Username:</label>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label class="h5" for="id_password">Password:</label>
            {{ form.password }}
        </div>
        <button class="button-primary button-lg" type="submit"><i class="fa-solid fa-right-to-bracket fa-lg m-auto"></i>Login</button>
    </form>
</div>

{% endblock content %}